[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = { $ref = "PORT" }

[services.web]
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.postgres]
image = "postgres:15"