"use strict";(self.webpackChunkgoaix_backend=self.webpackChunkgoaix_backend||[]).push([[541],{541:(x,D,s)=>{s.r(D),s.d(D,{default:()=>S});var t=s(92132),_=s(21272),d=s(38413),c=s(55356),O=s(85963),A=s(4198),o=s(94061),h=s(83997),f=s(30893),C=s(90151),p=s(68074),l=s(7441),v=s(7537),g=s(88875),i=s(37565),I=s(54514),r=s(83925),E=s(93337),M=s(61535),L=s(54894),W=s(63891),u=s(12083),a=s(91373),e=s(8105),T=s(74930);const j=u.Ik().shape({restrictedAccess:u.zM(),password:u.Yj().when("restrictedAccess",(n,m)=>n?m.required(i.iW.required):m)}),S=()=>{(0,i.L4)();const{formatMessage:n}=(0,L.A)(),{submit:m,data:U,isLoading:$}=(0,e.u)(),[B,H]=(0,_.useState)(!1),{allowedActions:N}=(0,i.ec)(a.P),Q=R=>{m.mutate({prefix:U?.prefix,body:R})};return(0,t.jsx)(d.g,{children:$?(0,t.jsx)(i.Bl,{children:"Plugin settings are loading"}):(0,t.jsx)(M.l1,{initialValues:{restrictedAccess:U?.documentationAccess.restrictedAccess||!1,password:""},onSubmit:Q,validationSchema:j,children:({handleSubmit:R,values:P,handleChange:V,errors:K,setFieldTouched:Y,setFieldValue:y,dirty:z})=>(0,t.jsxs)(i.lV,{noValidate:!0,onSubmit:R,children:[(0,t.jsx)(c.Q,{title:n({id:(0,e.g)("plugin.name"),defaultMessage:"Documentation"}),subtitle:n({id:(0,e.g)("pages.SettingsPage.header.description"),defaultMessage:"Configure the documentation plugin"}),primaryAction:(0,t.jsx)(O.$,{type:"submit",startIcon:(0,t.jsx)(I.A,{}),disabled:!z&&N.canUpdate,children:n({id:(0,e.g)("pages.SettingsPage.Button.save"),defaultMessage:"Save"})})}),(0,t.jsx)(A.s,{children:(0,t.jsx)(o.a,{background:"neutral0",hasRadius:!0,shadow:"filterShadow",paddingTop:6,paddingBottom:6,paddingLeft:7,paddingRight:7,children:(0,t.jsxs)(h.s,{direction:"column",alignItems:"stretch",gap:4,children:[(0,t.jsx)(f.o,{variant:"delta",as:"h2",children:n({id:"global.settings",defaultMessage:"Settings"})}),(0,t.jsxs)(C.x,{gap:4,children:[(0,t.jsx)(p.E,{col:6,s:12,children:(0,t.jsx)(l.l,{name:"restrictedAccess",label:n({id:(0,e.g)("pages.SettingsPage.toggle.label"),defaultMessage:"Restricted Access"}),hint:n({id:(0,e.g)("pages.SettingsPage.toggle.hint"),defaultMessage:"Make the documentation endpoint private"}),checked:P.restrictedAccess,onChange:()=>{P.restrictedAccess===!0&&(y("password","",!1),Y("password",!1,!1)),y("restrictedAccess",!P.restrictedAccess,!1)},onLabel:"On",offLabel:"Off"})}),P.restrictedAccess&&(0,t.jsx)(p.E,{col:6,s:12,children:(0,t.jsx)(v.k,{label:n({id:"global.password",defaultMessage:"Password"}),name:"password",placeholder:"**********",type:B?"text":"password",value:P.password,onChange:V,error:K.password?n({id:K.password,defaultMessage:"Invalid value"}):null,endAction:(0,t.jsx)(w,{onClick:F=>{F.stopPropagation(),H(G=>!G)},label:n(B?{id:"Auth.form.password.show-password",defaultMessage:"Show password"}:{id:"Auth.form.password.hide-password",defaultMessage:"Hide password"}),children:B?(0,t.jsx)(r.A,{}):(0,t.jsx)(E.A,{})})})})]})]})})})]})})})},w=(0,W.Ay)(g.T)`
  svg {
    height: 1rem;
    width: 1rem;
    path {
      fill: ${({theme:n})=>n.colors.neutral600};
    }
  }
`},8105:(x,D,s)=>{s.d(D,{g:()=>O,u:()=>A});var t=s(21272),_=s(37565),d=s(74930),c=s(91373);const O=o=>`${c.p}.${o}`,A=()=>{const o=(0,_.hN)(),{del:h,post:f,put:C,get:p}=(0,_.ry)(),{formatAPIError:l}=(0,_.wq)(),{isLoading:v,isError:g,data:i,refetch:I,error:r}=(0,d.useQuery)(["get-documentation",c.p],async()=>{const{data:a}=await p(`/${c.p}/getInfos`);return a});(0,t.useEffect)(()=>{g&&r&&o({type:"warning",message:r?l(r):{id:"notification.error"}})},[g,r,o,l]);const E=a=>{o({type:"warning",message:l(a)})},M=(a,e,T)=>{I(),o({type:a,message:{id:O(e),defaultMessage:T}})},L=(0,d.useMutation)(({prefix:a,version:e})=>h(`${a}/deleteDoc/${e}`),{onSuccess:()=>M("info","notification.delete.success","Successfully deleted documentation"),onError:E}),W=(0,d.useMutation)(({prefix:a,body:e})=>C(`${a}/updateSettings`,e),{onSuccess:()=>M("success","notification.update.success","Successfully updated settings"),onError:E}),u=(0,d.useMutation)(({prefix:a,version:e})=>f(`${a}/regenerateDoc`,{version:e}),{onSuccess:()=>M("info","notification.generate.success","Successfully generated documentation"),onError:E});return{data:i,isLoading:v,isError:g,remove:L,submit:W,regenerate:u}}}}]);
